name: GitHub Actions - CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew clean build koverVerify koverXmlReport
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ${{ github.workspace }}/build/reports/kover/report.xml
      env:
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
